#!/usr/bin/env python
# encoding: utf-8
"""
@author: Aurélien Gâteau <aurelien.gateau@free.fr>
@license: GPL v3 or later
"""
import os
import sys
from argparse import ArgumentParser

import vobject

import tui

def get_action_list():
    return [x[4:] for x in globals() if x.startswith("act_")]

def act_edit(card):
    while True:
        firstname = card.n.value.given
        lastname = card.n.value.family

        print ""
        print u"First name: %s, Last name: %s, fn: %s" % (firstname, lastname, card.fn.value)
        answer = tui.editLine(None, prompt="Edit, Swap, Delete, Validate: (esdV) ").lower()
        if answer == "e":
            firstname = tui.editLine(firstname, prompt="First name: ")
            lastname = tui.editLine(lastname, prompt="Last name: ")
        elif answer == "s":
            firstname, lastname = lastname, firstname
        elif answer == "d":
            return False
        elif answer in ("", "v"):
            return True
        else:
            print "Invalid answer"
            continue

        # We reach this point if a change was made
        card.n.value.given = firstname
        card.n.value.family = lastname
        card.fn.value = "%s %s" % (firstname, lastname)

def act_clean_fr_phones(card):
    if not "tel" in card.contents:
        return True

    for tel in card.tel_list:
        print "%s params=%s:" % (tel.value, repr(tel.params))
        value = tel.value

        if "-" in value:
            print "- Removing '-'"
            value = value.replace("-", "")
        if value[0] == "0" and value[1] in "123456":
            print "- Turning leading 0 in +33"
            value = "+33" + value[1:]
        if value.startswith("+336") and not u"CELL" in tel.params["TYPE"]:
            print "- Marking as a cellphone"
            if u"VOICE" in tel.params["TYPE"]:
                tel.params["TYPE"].remove(u"VOICE")
            tel.params["TYPE"].append(u"CELL")
        tel.value = value

        print "  => %s params=%s:" % (tel.value, repr(tel.params))

    return True


def act_title(card):
    firstname = card.n.value.given.title()
    lastname = card.n.value.family.title()
    card.n.value.given = firstname
    card.n.value.family = lastname

    lst = [card.n.value.prefix, lastname, firstname, card.n.value.additional, card.n.value.suffix]
    fn = " ".join([x for x in lst if x])
    card.fn.value = fn
    return True


def main():
    parser = ArgumentParser()
    parser.add_argument("action", choices=get_action_list(), help="Action to perform")
    parser.add_argument("in_vcf", help="Input file")
    parser.add_argument("out_vcf", help="Output file", nargs='?')

    args = parser.parse_args()

    action = eval("act_" + args.action)

    src_file = open(args.in_vcf)

    out_vcf = args.out_vcf
    if not out_vcf:
        out_vcf = args.in_vcf + '.new'
    dst_file = open(out_vcf, "w")

    for card in vobject.readComponents(src_file):
        if not "fn" in card.contents:
            print "no FN in", card, "discarding"
            continue
        keep = action(card)
        if keep:
            while len(card.fn_list) > 1:
                del card.fn_list[-1]
            dst_file.write(card.serialize())
            dst_file.write("\r\n")

    if not args.out_vcf:
        os.rename(out_vcf, args.in_vcf)
    return 0

if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
